### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by KyrVorga** [mschnitzer/ark-survival-ascended-linux-container-image#1]
Hey!

Thanks for making this. Just as I struggled to figure out how to get it working, this appears.
I've successfully set it up on my unRAID server with little trouble.

I noted that you mentioned the server being non-queryable. Is that a limitation of the actual dedicated server program?

Thanks again!

**Comment by mschnitzer** [comment]
Hey,

glad to hear that you were able to get your server running!

As for the Query Port: I didn't find evidence of the server attempting to bind any query port and the server doesn't bind anything when you attempt to bind a query port with ?QueryPort=12345 as start parameter. This feature seems to be missing for ASA, but was definitely there for ASE. Also my previous query scripts that I wrote for ASE don't seem to be able to run any sort of query.

I guess this is because ASA does no longer announce themselves to the Steam master server and there's also no entry in the Steam server browser for ASA (only ASE).

My speculation is that they are now using different master servers (very likely because of the future crossplay functionality) so that they decided to step away from Valves Source Query protocol.

Obviously this is just pure speculation based on the fact that the server is no longer binding any query port, nor can any ASA server be found on the Steam master list.

**Comment by mschnitzer** [comment]
However, the RCON protocol seems to be the same and I'm able to connect to port 27020 (TCP) and run RCON commands like listing players or kicking somebody. So at least you could still query how many players are on that server through RCON.

**Comment by KyrVorga** [comment]
That was very informative thanks. Here's hoping Wildcard sort something nice out for us for once.
