### ISSUE TITLE
Checking the running state of the server.

### ISSUE THREAD

**Issue by bedrockbusters** [mschnitzer/ark-survival-ascended-linux-container-image#17]
Got a quick question. Is there a way to check the running state of the server? If I'm not sure if the server is running or not, is there a command to check? 
Also, check the last time the server was saved. I know I can navigate to the save directory run "ls -la" and see the last time the save file was modified, but that's a little tedious.

**Comment by mschnitzer** [comment]
`docker ps` shows you all running containers. `docker ps -a` shows you all containers that are stopped or were killed otherwise.

`docker inspect asa-server-1` shows you all details of your container, including why it crashed (e.g. out of memory). Obviously, ASA specific crashes won't be identified by docker, just the container exit code.

As for checking whether the savegame was saved: I don't see any other way than checking when the files were modified. But why exactly do you want to check it that often? If you want to be extra sure, you can run `admincheat saveworld` before you leave the server (given you are logged in as admin ingame).

**Comment by mschnitzer** [comment]
@bedrockbusters has your question been answered?

**Comment by bedrockbusters** [comment]
Yes. Thank you very much!

**Comment by mschnitzer** [comment]
Thanks for confirming this, closing now. Feel free to open another issue if you have any further questions.
