### ISSUE TITLE
Server crashes - UnknownFunction

### ISSUE THREAD

**Issue by mahmut-tu** [mschnitzer/ark-survival-ascended-linux-container-image#22]
The server keeps crashing randomly. I could not find any specific reason for this. If found this crashstack in the volumes log folger, if that helps.

`F a t a l   e r r o r ! 
 
 
 
 U n h a n d l e d   E x c e p t i o n :   E X C E P T I O N _ A C C E S S _ V I O L A T I O N   w r i t i n g   a d d r e s s   0 x 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 8 
 
 
 
 C L :   4 5 0 6 9 6   
 
 0 x 0 0 0 0 0 0 0 2 c 7 4 8 5 6 8 7   u c r t b a s e . d l l ! U n k n o w n F u n c t i o n   [ ] 
 
 0 x 0 0 0 0 0 0 0 2 c 7 4 c 9 0 3 d   u c r t b a s e . d l l ! U n k n o w n F u n c t i o n   [ ] 
 
 0 x 0 0 0 0 0 0 0 1 4 3 e 2 e 3 4 8   A r k A s c e n d e d S e r v e r . e x e ! U n k n o w n F u n c t i o n   [ ] 
 
 Last Replicated Actor UDS_Island_C_1
Last Remote Function PlayHitEffectPoint
`

**Comment by mschnitzer** [comment]
Do you have any mods installed?

**Comment by mschnitzer** [comment]
I cannot say this for sure, but I'd say it's either ASA server software or mod related.

I personally never had any crash on my vanilla server since day one, but I also do not use any mods. This error message does not sound like it's an issue with the container image, rather gameplay related/servercode related. So either you have triggered a bug in the ASA server software or a mod is causing this.
