### ISSUE TITLE
Server is not starting: Failed to reserve range

### ISSUE THREAD

**Issue by Weofi** [mschnitzer/ark-survival-ascended-linux-container-image#37]
Hey, i tried to setup the ARK Server but i ran into this error:

![image](https://github.com/mschnitzer/ark-survival-ascended-linux-container-image/assets/54805839/75f14cbe-0449-44e8-9717-36cab17c1b5f)

i can do `docker exec asa-server-1 cat server-files/ShooterGame/Saved/Config/WindowsServer/GameUserSettings.ini | grep SessionName` for like 20s and then the container crashes or something and i get this:

`Error response from daemon: Container 178c040b9df1fb47c576363fadec210ed825b58fe09a2229fc639e2c443bd7b5 is not running`

I only have 8gb of Ram on this server. i dont know if this might be the problem.

Any Suggestions?

**Comment by mschnitzer** [comment]
I'd go for a minimum of 11 GB at least. This is what a vanilla server without any mods consumed for me while testing. They might have improved the RAM usage meanwhile, but I'm pretty sure not to that extend and even if, 8 GB would be too less for actually playing on it.

Could you please run the following command once the container gets killed and check if Out of Memory is actually the issue?
```
docker inspect asa-server-1| grep OOM
```

If it says "OOMKilled: true" then the container ran out of memory.

If it says false, then it might have been something else or the ASA server killed itself because it ran out of memory before the container notices it. So in anyway, I'd test it with 11 GB of RAM.

**Comment by Weofi** [comment]
thx for the fast replay.

`"OOMKilled": true,` it is ^^ i try to upgrade to more ram

**Comment by mschnitzer** [comment]
That will very likely solve your issue. Please reopen in case it didn't.

**Comment by Weofi** [comment]
more ram and it works perfectly. thanks :D
