### ISSUE TITLE
docker-compose up -d rebuilds the entire container

### ISSUE THREAD

**Issue by thomasmcrowe** [mschnitzer/ark-survival-ascended-linux-container-image#40]
I often run docker-compose up -d because I change the starting parameters often (usually adding and removing mods). About 1 out of every 4 or 5 times instead of just doing a quick "updating settings" it instead rebuilds a whole new docker instances with its only files and server and all. It puts it under /var/snapd instead of /var/lib/docker and I am forced to move over my saved games and ini's. This is pretty annoying and I'd like to figure out why it keeps doing a whole new rebuild. Any logs I can run or something I should check next time I run docker-compose up?

**Comment by mschnitzer** [comment]
Could you please share your `docker-compose.yml` file and censor all passwords that you might have placed there?

What distribution are you using?

**Comment by thomasmcrowe** [comment]
https://pastebin.pl/view/af8678d2

Ubuntu 22.04

**Comment by mschnitzer** [comment]
So it is an expected behavior of docker-compose that the container rebuilds if you change the `docker-compose.yml` file, but this does not have any effect on docker volumes where your server files are stored.

I'm actually not sure what you mean by "It puts under `/var/snapd`". The ASA files are stored in docker volumes and those can be found at `/var/lib/docker/volumes`. Could you please show me what files are stored at `/var/snapd`. This is the first time I hear about this.

**Comment by thomasmcrowe** [comment]
Yes, the original install built the container in /var/lib/docker as
expected. However after running docker-compose up -d several times over a
week, it didn't do its normal 20 second rebuild, it downloaded the data
again and rebuilt a new container and put it under /var/snapd.

It does not recognize the original build and no longer uses those volumes.

**Comment by mschnitzer** [comment]
Could you please show me what files exist in `/var/snapd` ?

**Comment by mschnitzer** [comment]
Please reopen if you still need help.
