### ISSUE TITLE
user friendly environments

### ISSUE THREAD

**Issue by banzoola** [mschnitzer/ark-survival-ascended-linux-container-image#77]
due to another issue i've been changing the ports and found it niggly updating the wall of text "ASA_START_PARAMS="

if you add the below script to the docker file and update the entry point in the compose file to point to the script it will accept parameters like this.

    environment:
      - PORT=7789
      - RCON_PORT=27020
      - RCON_ENABLED=True
      - MAX_PLAYERS=50
      - CLUSTER_ID=default
      - CLUSTER_DIR="/home/gameserver/cluster-shared"
      - ENABLE_DEBUG=0

nano ~/entrypoint.sh

#!/bin/bash

ASA_START_PARAMS="TheIsland_WP?listen?Port=${PORT}?RCONPort=${RCON_PORT}?RCONEnabled=${RCON_ENABLED} -WinLiveMaxPlayers=${MAX_PLAYERS} -clusterid=${CLUSTER_ID} -ClusterDirOverride=${CLUSTER_DIR}"

export ASA_START_PARAMS

exec /usr/bin/start_server

**Comment by mschnitzer** [comment]
I understand that someone sees this as an ugly way to configure their server that way. However, I think we should stick to that way, just because in ASA wiki, reddit posts, and forums, people always refer to command line arguments and how it can be adjusted. If we would change it to environment variables, people start thinking that all command line arguments need to be configured that way. I want to stay as close as possible to the original behavior.

**Comment by banzoola** [comment]
that makes sense, totally understand your logic on it. Thanks
