### ISSUE TITLE
Server wont show up in list

### ISSUE THREAD

**Issue by AxoIsAxo** [mschnitzer/ark-survival-ascended-linux-container-image#86]
![image](https://github.com/user-attachments/assets/7fcbb60d-7c10-42be-ab0a-0279245719f6)
Starting the ARK: Survival Ascended dedicated server...
Start parameters: TheIsland_WP?listen?Port=7777?RCONPort=27020?RCONEnabled=True -WinLiveMaxPlayers=50 -clusterid=default -ClusterDirOverride="/home/gameserver/cluster-shared" 
esync: up and running.
Failed to read /etc/machine-id, error Invalid argument.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
^C
axoisaxo@pop-os:~/asa-server$ docker exec asa-server-1 cat server-files/ShooterGame/Saved/Config/WindowsServer/GameUserSettings.ini | grep SessionName
permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/asa-server-1/json": dial unix /var/run/docker.sock: connect: permission denied
axoisaxo@pop-os:~/asa-server$ sudo docker exec asa-server-1 cat server-files/ShooterGame/Saved/Config/WindowsServer/GameUserSettings.ini | grep SessionName
SessionName=ARK #596393
axoisaxo@pop-os:~/asa-server$ sudo docker exec asa-server-1 cat server-files/ShooterGame/Saved/Config/WindowsServer/GameUserSettings.ini | grep SessionName
SessionName=ARK #596393
axoisaxo@pop-os:~/asa-server$ sudo docker exec asa-server-1 cat server-files/ShooterGame/Saved/Config/WindowsServer/GameUserSettings.ini | grep SessionName
SessionName=ARK #596393
axoisaxo@pop-os:~/asa-server$

**Comment by mschnitzer** [comment]
[This](https://github.com/mschnitzer/ark-survival-ascended-linux-container-image?tab=readme-ov-file#server-is-not-visible-in-server-browser) addresses your problem.

**Comment by AxoIsAxo** [comment]
> [This](https://github.com/mschnitzer/ark-survival-ascended-linux-container-image?tab=readme-ov-file#server-is-not-visible-in-server-browser) addresses your problem.

I did all this

**Comment by mschnitzer** [comment]
On your screen "Show player servers" is unchecked. Did you check that box now?

**Comment by AxoIsAxo** [comment]
> On your screen "Show player servers" is unchecked. Did you check that box now?

Still wont work

**Comment by davidkinnes** [comment]
I'm having the same problem

**Comment by sdornieden** [comment]
I'm having the same issue.

Direct connect possible, but no Server-Browser listing.
Only 1 IP, CURL Testing shows the right IP.

**Comment by mschnitzer** [comment]
@davidkinnes ASA servers won't show up on the Steam server browser, only through the in game server browser. Most of the times it's really just a filter issue. I just started a fresh server last week and it shows up on the server browser immediately, running the latest updates.

What else did you all change? Also, start with a simple server name as well. I can imagine they do some filtering on that. Furthermore, ensure the password checkbox in the filter reflects whether your server has a password or not.

**Comment by mschnitzer** [comment]
Is it working now?

**Comment by szimre** [comment]
Having the same issues, I can connect to the server from the console no issues, but I can't get it to show up on the in-game server browser.
I have multiple IPs but I want to use the main one, CURL testing returns the correct value, plus https://www.battlemetrics.com/servers/arksa/ also lists my server (didn't add it manually so it must've pulled it from ARK) with all the correct details, even player numbers are correct if I join manually.

Initially I tried installing the server in a windows vm under proxmox, that didn't work for some reason, then I created a server on my local machine, I was in the same situation (manual connect ok but server not in browser) so today I tried this tool on my hosted server and I'm still here. I'm using the Microsoft Store version and tried every possible filter combination in the last 2 days. I'm at the verge of buying the game on Steam to see if that works.

It was so simple to run ARK SE servers, I really hate what they did with SA regarding hosting your own servers...

**Comment by szimre** [comment]
Update: Works absolutely fine if I start the game on steam without BattlEye, server instantly showed up in server browser. Not sure this is something you can do with the shitty Microsoft Store version, so fuck that, but we'll just switch to Steam, game is on sale anyways.

**Comment by mschnitzer** [comment]
I didn't verify this, but if it's similar to other games, then the Windows Store and Steam store version are two different systems which would require you to enable crossplay on the Steam ASA server in order to play on it with the Windows Store version. This might be the reason why I didn't show up. But as I said, it's just a guess.

I'm closing this issue now, as there's now reply from the author of this issue anymore and your issue (szimre) seems to be resolved as well.

**Comment by szimre** [comment]
Thanks!
I'm not fully aware of how GitHub comments work on issues, so hopefully I'm not reopening this issue by posting an additional comment.
Just wanted to let you know know that ever since we switched to the steam version of the game we had no trouble discovering the server using the in-game browser (well, that's not true, every time we want to join we have to re-check all the filter states ARK might have reset randomly and enter the server name manually and press refresh to see the server, but we pretty much accepted this as the price of not hosting the server on fucking Nitrado).
Long story short everyone learned this little ceremony and we have no trouble playing with friends.

I had everyone re-check (before uninstalling) to see if they see the server in the Microsoft Store/XBOX Game Pass PC version of the game and the answer is always the same, it never shows up, so you might want to extend the README with this info to cut down on the number of new issue tickets. 

I mean honestly it was a rookie mistake to expect anything related to MS to work properly but since we were already subscribed to Game Pass for another game it seemed like a free shortcut to try the new ARK. Won't make the mistake of trusting Microsoft again.
