### ISSUE TITLE
asa-server-set-promissions container will not start 

### ISSUE THREAD

**Issue by UncensoredCobra** [mschnitzer/ark-survival-ascended-linux-container-image#92]
asa-server-set-promissions container will not start i did everything step by step but i noticed after that the set permissions wasnt started so i tried to start it and it gave exit code 0 on portainer. here is th elog file i can see from portainer 
[_asa-server_set-permissions-1_1_logs.txt](https://github.com/user-attachments/files/18146680/_asa-server_set-permissions-1_1_logs.txt)

**Comment by mschnitzer** [comment]
The set-permissions container starts and exits, because it is just needed as a preparation for the ASA server container which will be started right after. It is only being used to set the right permissions, so that you don't run into issues if you have files owned by another user other than the ASA uid and gid (25000:25000). Don't worry about it.
